sudo: false

language: ruby

rvm:
  - 2.4.0

env:
  - GIT_DEPLOY_REPO=https://$GITHUB_TOKEN@github.com/TangleID/docs.git

branches:
  only:
    - develop

cache: bundler
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./deploy-ci.sh; fi'
